[workspace]
resolver="2"
members=[".", "scripts"]
default-members=["scripts", "."]

[package]
name="wasm-testsuite"
version="0.3.0"
description="Generic test harness for WebAssembly Runtimes"
license="Apache-2.0 OR MIT"
readme="README.md"
edition="2021"
include=["src/**/*", "data/**/*", "Cargo.toml"]

[dependencies]
include_dir="0.7.4"
wast={version="221", optional=true}

[dev-dependencies]
eyre="0.6"

[features]
default=["wast"]
wast=["dep:wast"]
